### ISSUE TITLE
API 요청 시 header 관련

### ISSUE THREAD

**Issue by Mindohyeon** [SLTDV/Choice-iOS#47]
## Title
Alamofire 에서는 Request 를 보낼 때
encoding 에 쓰이는 ParameterEncoding 프로토콜이 Content-Type을 application/json으로 초기화 해줍니다.

따라서 현재 모든 API 요청 시 쓰이는 AF.request 구문에서 
header에  ["Content-Type" : "application/json"] 를 사용하고 있는 부분을 제거해도 될 것 같습니다.

## ref
[Alamofire/Content-Type](https://dohyeon-dev.tistory.com/5)

**Comment by Heeesang** [comment]
오! 좋습니다 🙃
