### ISSUE TITLE
프로필 이미지 업로드 관련

### ISSUE THREAD

**Issue by Mindohyeon** [SLTDV/Choice-iOS#60]
## Ttile
프로필 이미지 업로드 시 불필요한 서버 요청이 있습니다.

## Description
**용어 정리**
       * default image :  "person.crop.circle.fill"  <img width="27" alt="스크린샷 2023-04-06 오후 12 04 49" src="https://user-images.githubusercontent.com/81687906/230262102-bfa3197b-d62c-4888-be08-4f2d7e4ad311.png">

회원가입 시 ```profileImageView``` 가 default image 로 초기화 되어있기 때문에,
사용자가 프로필 이미지를 설정하지 않아도 회원가입 시 default image를 서버에 업로드 요청을 하게됩니다.

즉,  image가 옵셔널임에도 서버로 nil을 보낼 수 없고, 불필요한 서버 통신에 오버헤드가 발생합니다.

## Therefore
사용자가 프로필 이미지를 설정하지 않으면 서버에 이미지 업로드 API 요청 자체를 하지 않고,
프로필 이미지를 사용해야 할 때마다 nil check 를 통해서 default image 를 설정해주는건 어떨까요?

**Comment by Heeesang** [comment]
이 이슈로 인해 프로필에서 default image 가 깨지는 현상도 있었던것 같습니다. default image는 API 통신을 하지 않고 설정 하는 방법이 좋아보입니다!😀 찬성🤝
